import type { NextPage } from "next";
import Head from "next/head";
import mongoose from "mongoose";
import orderModel from "../models/orders";
import type order from "../interface/order";

interface Props {
  orders: order[];
}
const Orders: NextPage<Props> = ({ orders }) => {
  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>{orders.map((el) => el.quantity)}</main>
    </>
  );
};

export async function getServerSideProps() {
  const conn = await mongoose.connect(
    "mongodb://127.0.0.1:6000/ecommerse?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.4.2"
  );
  const orders: order[] = await orderModel.find();
  return {
    props: { orders },
  };
}

export default Orders;
