import type { NextPage } from "next";
import Head from "next/head";
import mongoose from "mongoose";
import userModel from "../models/user";
import user from "../interface/user";
import Header from "../components/Header";

interface Props {
  user: user;
}
const User: NextPage<Props> = ({ user }) => {
  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header user={user} />
      <main className="h-screen flex items-center justify-center">
        <div className="flex-1 flex flex-col items-center">
          <img
            src={`https://avatars.dicebear.com/api/initials/${user.name}.svg`}
            alt=""
            className="w-1/3 rounded-full mb-5"
          />
          <p className="text-2xl">{user.name}</p>
          <p className="text-l text-gray-500">{user.email}</p>
        </div>
        <div className="flex-1"></div>
      </main>
    </>
  );
};

export async function getServerSideProps() {
  const conn = await mongoose.connect(
    "mongodb://127.0.0.1:6000/ecommerse?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.4.2"
  );
  const user = await userModel.find<user>();
  return {
    props: {
      user: JSON.parse(JSON.stringify(user[0])),
    },
  };
}

export default User;
